import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../containers/layout/Layout'
import LandingPage from './home/LandingPage'
import PopularCryptocurrencies from './home/PopularCryptocurrencies'
import CryptoPortfolio from './home/CryptoPortfolio'
import BinancePossibilities from './home/BinancePossibilities'
import NeedHelp from './home/NeedHelp'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Cryptocurrency Exchange</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <LandingPage />
      <PopularCryptocurrencies />
      <CryptoPortfolio />
      <BinancePossibilities />
      <NeedHelp />
    </Layout>
  </>
)

export default Home
