import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../containers/layout/Layout'
import TitleBanner from '../components/title-banner/TitleBanner'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Cryptocurrency Exchange</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <div>
        <TitleBanner firstTitle="Home" lastTitle="Page" />
      </div>
    </Layout>
  </>
)

export default Home
