import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../containers/layout/Layout'
import LandingPage from './home/LandingPage'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Cryptocurrency Exchange</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <LandingPage />
    </Layout>
  </>
)

export default Home
